services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - uv.lock
            - .venv
        - action: rebuild
          path: ./backend/uv.lock

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: ["pnpm", "run", "dev", "--host"]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
            - pnpm-lock.yaml
            - package.json
        - action: rebuild
          path: ./frontend/pnpm-lock.yaml

  db:
    image: postgres:16-alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db-data: